// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdnypltoetjvzimkbamy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbnlwbHRvZXRqdnppbWtiYW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTgzMjAsImV4cCI6MjA2MTE5NDMyMH0.Z4WbpJPZrz1GWe2NJt4y-tMJzTVa0bFEQLDDiiczhPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);